### ISSUE TITLE
app script editor addon publised using API/script

### ISSUE THREAD

**Issue by zffocussss** [gsuitedevs/apps-script-samples#101]
Hello Team:
                  My company run a google doc addon which is sure an appscript project.Now I can use Clasp(which is a node.js tool) to push and make deployment .but when it comes to publish on chrome web store .I have to do it by hand.
1.select specific version
2.click "update web store draft"
3.click "publish changes"

Can these step be taken automatically? I try to find some API,but it is not useful for me.

**Comment by sqrrrl** [comment]
Unfortunately there's no API for the publishing side of things at the moment. Chrome web store did have an API for publishing, but there's no equivalent for the G Suite Marketplace.

**Comment by sqrrrl** [comment]
Marking as wontfix since it's unlikely that this will be automatable any time soon.
