### ISSUE TITLE
Advanced Reports example fails to return results 

### ISSUE THREAD

**Issue by ianhyzy** [gsuitedevs/apps-script-samples#103]
## Expected Behavior

Sample URL: https://github.com/gsuitedevs/apps-script-samples/blob/master/advanced/adminSDK.gs 
Description: Trying to copy the user usage report to get docs owned and last login time

## Actual Behavior
Script now returns "No results returned"

## Steps to Reproduce the Problem

1. Copy and paste the script into a project
1. enable the advanced APIs
1. Run and see output

**Comment by erickoledadevrel** [comment]
It looks like the data may not be available from a week ago due to a blip in the reporting pipeline. Try adjusting the target date to another day. I've got PR #104 out to log warnings to make this case more clear.

**Comment by ianhyzy** [comment]
Thanks for responding! I did have data in the reporting pipeline but using the code from your PR fixed everything, and I can see the data now. Was that due to the old time zone function being used?
