### ISSUE TITLE
Locked file

### ISSUE THREAD

**Issue by nicolairobles** [gsuitedevs/apps-script-samples#106]
https://github.com/gsuitedevs/apps-script-samples/blob/db3ad6816484c1ba9707d34e17d1916713b28007/advanced/bigquery.gs#L91

**Comment by sqrrrl** [comment]
Can you clarify what the issue is?

**Comment by erickoledadevrel** [comment]
The hosted CSV file referenced in the sample somehow lost public read access. I've restored it now.
