### ISSUE TITLE
Exaple script Fails with error "Invalid number of arguments provided. Expected 0-1 only"

### ISSUE THREAD

**Issue by somesh101** [gsuitedevs/apps-script-samples#110]
Example URL: https://github.com/gsuitedevs/apps-script-samples/blob/master/advanced/youtubeAnalytics.gs

## Expected Behavior
 returns response object:  Or json

Description: 
i just copy pasted the code and tried to run after replaceing my channel ID but error. 

## Actual Behavior 
Invalid number of arguments provided. Expected 0-1 only"
Avalaible syntax of the functions available is 
var result = YouTubeAnalytics.Reports.query();
var result = YouTubeAnalytics.Reports.query(Object optional arguments);

but the example contains 

 var result = YouTubeAnalytics.Reports.query('channel==' + channelId,
      formatDateString(lastMonth),
      formatDateString(today),
      metrics.join(','),
      options);

## Steps to Reproduce the Problem
1. Just copy paste your own code and run.

**Comment by erickoledadevrel** [comment]
The current code was written for v1 of the API, which has been deprecated. I've updated the code in https://github.com/gsuitedevs/apps-script-samples/commit/f79f2d2224b6ee8743b820abc396097ada8f1218 to work with v2 of the API, and I'm working to update the documentation to match.
