### ISSUE TITLE
How to use google calendar part ?

### ISSUE THREAD

**Issue by nagacoder** [gsuitedevs/apps-script-samples#112]
## Expected Behavior

Description: i just want to test google calender section , but i  don't know its work or not, 

## Steps to Reproduce the Problem

1. i follow this link to create Script App https://developers.google.com/apps-script/guides/import-export
2. copy file from calender folder to my google script
3. deploying with manifest file, 

How can i know this work fine or not?
<img width="1208" alt="ff" src="https://user-images.githubusercontent.com/32693625/56715093-e0f22e00-6760-11e9-99cf-aa78c2c1eb0d.png">

**Comment by sqrrrl** [comment]
Thanks for trying things out. Unfortunately this issue tracker is only for issues with the sample code, and it's not clear from issue which particular sample this applies to. For general help about apps script, I suggest trying some of the community resources at https://developers.google.com/apps-script/support
