### ISSUE TITLE
Gmail add-on - label example does note update labels in real-time

### ISSUE THREAD

**Issue by roojs** [gsuitedevs/apps-script-samples#115]
## Expected Behavior

Update Gmail Labels, in real time, and show the correct labels in add-on

Sample URL: https://github.com/gsuitedevs/apps-script-samples/blob/master/gmail/add-ons/quickstart.gs
Description:  Simple add-on to modify the labels of a message

## Actual Behavior
Adding a label, does not update the label on the currently viewed email. - flipping to another message, and back will show it on the email
Going to an email with a tag, then removing it, again does not update the email, but even worse, if you go back and view that email, with the label removed, the add-on shows the old list of labels. - Making the add-on practially useless.

## Steps to Reproduce the Problem

1. set up the add-on
2. go to a message - add a couple of labels on the add-on
3. look at the message - it does not change.

**Comment by sqrrrl** [comment]
More of an issue with how gmail itself works than the sample. Gmail doesn't update in real time like that. You can even reproduce with applying labels to messages in separate tabs and see how changes aren't immediately reflected.

**Comment by roojs** [comment]
But creating a demo that doesn't really work - does not make the whole 'add-on' feature look very good. You would be better just deleting that demo, and replacing it with something that is at least works..
