### ISSUE TITLE
API to create pdf from slides

### ISSUE THREAD

**Issue by baymac** [gsuitedevs/apps-script-samples#119]
For example,

In Docs,

we can get the document blob of the document by

```
var docblob = DocumentApp.getActiveDocument().getAs('application/pdf')
```

I think this is because when you call `SlidesApp.getActivePresentation()` it contains some meta data like speaker notes. Since download as pdf is available in UI I think there should be a way to do it in the appscript but there is no api for that.

**Comment by baymac** [comment]
I able to get the pdf of the slide by:

```
var id = SlidesApp.getActivePresentation().getId();
var slideblob = DriveApp.getFileById(id).getAs('application/pdf');
```

But I am sure there's got to be a more sane way of doing this.

**Comment by erickoledadevrel** [comment]
This issue tracker is only meant for issues with the sample code in this repo. To learn how to report missing features, see this section of the Apps Script support page:

https://developers.google.com/apps-script/support#missing_features
