### ISSUE TITLE
Google Apps Script to blogger API

### ISSUE THREAD

**Issue by catafest** [gsuitedevs/apps-script-samples#121]
## Expected Behavior
I try to access the https://developers.google.com/apis-explorer/#search/stats/m/blogger/v3/blogger.pageViews.get with Google Apps Script.
Sample URL:
Description:
```
function bloggerAPI() {
  
  var api = "https://www.googleapis.com/blogger/v3/users/self/blogs";
  
  var headers = {
    "Authorization": "Bearer " + getService().getAccessToken()
  };
  
  var options = {
    "headers": headers,
    "method" : "GET",
    "muteHttpExceptions": true
  };
  
  var response = UrlFetchApp.fetch(api, options);
  
  var json = JSON.parse(response.getContentText());
  
  for (var i in json.items) {
    Logger.log("[%s] %s %s", json.items[i].id, json.items[i].name, json.items[i].url); 
  } 
}
```
## Actual Behavior
ReferenceError: "getService" is not defined. (line 18, file "Code")
## Steps to Reproduce the Problem
1. write the code
1. the project is link for authorization
1.I got the error

**Comment by oshliaer** [comment]
Hi!

Just replace the line 18, file "Code" with `Authorization": "Bearer " + ScriptApp.getOAuthToken()`. After that open the manifest file and add at least the next json:

```json
{
  "timeZone": "Europe/Moscow",
  "dependencies": {
  },
  "exceptionLogging": "STACKDRIVER",
  "oauthScopes": [
    "https://www.googleapis.com/auth/blogger",
    "https://www.googleapis.com/auth/script.external_request"
  ]
}
```

It should be fine.

**Comment by sqrrrl** [comment]
For general support, see https://developers.google.com/apps-script/support

**Comment by catafest** [comment]
Because I start with Apps Script and try to use the project ... according to this note:

_Warning: Starting on or after April 8, 2019, the Google Cloud Platform Console won't be able to access the default GCP projects created for new Apps Script projects. Older, existing scripts may have default GCP projects that are still accessible, however. If you have a new script and require access to its GCP project from the Google Cloud Platform Console, you must use a standard GCP project._
[https://developers.google.com/apps-script/guides/cloud-platform-projects#standard_cloud_platform_projects](https://developers.google.com/apps-script/guides/cloud-platform-projects#standard_cloud_platform_projects)

The error is clear :
```
You do not have sufficient permissions to view this page
There was an error while loading /apis/credentials/consent?folder=&organizationId=&project=xxxx.

You are missing at least one of the following required permissions:
Project

clientauthconfig.brands.get
oauthconfig.verification.get
resourcemanager.projects.get
```
