### ISSUE TITLE
Bug in sample MailApp code

### ISSUE THREAD

**Issue by ripperdoc** [gsuitedevs/apps-script-samples#129]
In the `apps-script-samples/gmail/sendingEmails/sendingEmails.gs` file, row 29, the line says:
` for (i in data) {`

This `i` is not properly declared with `var` and in my case it was seen as a string variable, meaning the later calculation of `startRow+i` where startRow was 2 became `20` (string concatenation) instead of `2`.

**Comment by sqrrrl** [comment]
#130 should fix this.

**Comment by sqrrrl** [comment]
Thanks @oshliaer :)
