### ISSUE TITLE
how can I pass the id and client for OAuth 2.0 authorization ?

### ISSUE THREAD

**Issue by SkillKota** [gsuitedevs/apps-script-samples#138]
I have an authorization function in Google Data Studio. How can I pass the id and client there to make a generic function.
My function now: 
function getOAuthService() {
return OAuth2.createService('exampleService')
    .setAuthorizationBaseUrl('https://oauth.yandex.ru/authorize')
    .setTokenUrl('https://oauth.yandex.ru/token')
    .setClientId(id)
    .setClientSecret(client) 
    .setPropertyStore(PropertiesService.getUserProperties())
    .setCallbackFunction('authCallback');
};

**Comment by erickoledadevrel** [comment]
This GitHub issue tracker is best at diagnosing specific issues with the samples contained within. For more generic Q&A about Apps Script please consult our support page:

https://developers.google.com/apps-script/support
