### ISSUE TITLE
onInstall troubleshooting 

### ISSUE THREAD

**Issue by yshterev** [gsuitedevs/apps-script-samples#140]
## Expected Behavior

`onInstall` should run and create a menu after add-on is installed

Sample URL: https://gsuite.google.com/marketplace/app/vizzlo_%E2%80%93_charts_business_graphics/201180685047
Description: Add-on for google slides - integration with vizzlo.com

## Actual Behavior
`onInstall` does not seem to run in my add-on when installed. I don't do more than just creating a menu. 

Some things to note:
- The app was converted to GCP project recently
- This worked before
- I get some errors when the app is installed in Google Slides, incognito mode. I am not sure how to debug it or if it is coming from my code:

![image](https://user-images.githubusercontent.com/6039417/75226017-4addc880-57b4-11ea-8fc5-be98bfaeaae7.png)

Can this error be blocking it?

Code looks like this:

```
function onOpen() {
    SlidesApp
        .getUi()
        .createAddonMenu()
        .addItem('Insert document', 'loadSidebar')
        .addItem('Update all documents in my presentation', 'menuSync')
        .addToUi();
}

function onInstall() {
    onOpen();
}
```

## Steps to Reproduce the Problem

1. Create a presentation
2. In main menu `Add-ons -> Get add-ons -> Search for Vizzlo and install it`
3. After installation is done menu 'Insert document' and 'Update all documents in my presentation' are missing in add-on menu.

![image](https://user-images.githubusercontent.com/6039417/75226338-e707cf80-57b4-11ea-92c1-2f44b0cdff75.png)

**Question**
Can I simulate `AuthMode.FULL` in dev mode so `onInstall` runs?
All I found is how to set `AuthMode.NONE` and `AuthMode.Limited`

**Comment by erickoledadevrel** [comment]
This issue tracker is only meant to report issues with samples in this repo. For reporting bugs, please see the support page: https://developers.google.com/gsuite/add-ons/editor-support
