### ISSUE TITLE
Calendar is not defined line 13 

### ISSUE THREAD

**Issue by laurainlv** [gsuitedevs/apps-script-samples#141]
## Expected Behavior

Sample URL:https://script.google.com/a/
Description: getting error for line 13 as not defined

## Steps to Reproduce the Problem

Followed all directions including enabling on API Console
![image](https://user-images.githubusercontent.com/61332746/75284407-95b60b00-57c9-11ea-807e-3115cbc87931.png)

**Comment by erickoledadevrel** [comment]
You need to enable the Advanced Calendar Service first: 

https://developers.google.com/apps-script/guides/services/advanced#enabling_advanced_services

More information here:

https://developers.google.com/apps-script/advanced/calendar

**Comment by laurainlv** [comment]
I enable this and it still provides the same error.  When I go to the api
console to enable it says I may need to create credentials.  But will not
allow me to do so for both sheets and calendar in the same place.

**Comment by erickoledadevrel** [comment]
Can you include a screenshot of the errors you are seeing, both in Apps Script and in the console?
