### ISSUE TITLE
There is some error

### ISSUE THREAD

**Issue by bjayaram** [gsuitedevs/apps-script-samples#21]
I tried both the demo instance and my own copy of Simple Tasks and both of them don't work for me in Firefox and Safari. I made sure the tasks API is enabled. It doesn't tell you what the error is but merely "An error has occurred, please try again".

Anyone else having this issue?

**Comment by bjayaram** [comment]
![screenshot 2017-03-06 17 32 30](https://cloud.githubusercontent.com/assets/3656277/23636496/e9a91d5e-0292-11e7-8930-97902d17b186.png)

**Comment by grant** [comment]
I wasn't able to reproduce the issue on Safari.
Did you find the issue on Chrome? It could possibly be a configuration error or temporary outage with the API.

Feel free to respond here and I can open up the issue.
