### ISSUE TITLE
Date calculated wrong

### ISSUE THREAD

**Issue by micksp** [gsuitedevs/apps-script-samples#23]
Hi 
I tried the dateadd function but found, strangely. that it sometimes calulates the dates wrongly. 
In my A4 cell i have a (dutch format) date: **1-9-2017**
In C4 I add: =DATEADD(A4; "M"; 1) this yields **1-10-2017**
But in my E4 Cell i added =DATEADD(C4; "M"; 1). This yields **30-10-2017**
Things get stranger because the next "hop" yields **1-12-2017** (correct) but the next **31-12-2017** (wrong)

I thought maybe the used library "Moment" has the problem, so I build a simple script to test this. However I cant reproduce the error from direct calls to the lib. I used the minified script that ships with the function (Moment.gs)

![screenshot_20170902_113602](https://user-images.githubusercontent.com/4571252/29994588-39dfedac-8fd3-11e7-906d-a4666acf7b42.png)
  

Am i missing something here?

**Comment by grant** [comment]
Hi Mick. The `Date` issues mentioned here are related to the following Date issues tracked here:
https://issuetracker.google.com/issues/36757698
https://issuetracker.google.com/issues/36762416

If there's a moment issue, that issue should be filed with [that library](https://github.com/moment/moment).
