### ISSUE TITLE
The helloworld script doesn't run?

### ISSUE THREAD

**Issue by OyeBenny** [gsuitedevs/apps-script-samples#39]
Mine doesn't run and says "Server error occurred. Please try saving the project again [Dismiss]" on three different Google accounts. So am I doing something wrong or is it the script?
Thank you.

**Comment by grant** [comment]
Are you still experiencing the error?
This might be a temporary server error.

**Comment by grant** [comment]
(I didn't see an error when trying to run the sample)

**Comment by erickoledadevrel** [comment]
There was an Apps Script outage due to a Cloud Console outage, details here: https://status.cloud.google.com/incident/developers-console/18003
