### ISSUE TITLE
Documented functional parameters of wrong type

### ISSUE THREAD

**Issue by SiddharthaSarma** [gsuitedevs/apps-script-samples#42]
Hi 

When I am going through the app-script-samples I found an issue that documentation of functional parameters are of Wrong type. Prefer refer to this [link ](https://github.com/gsuitedevs/apps-script-samples/blob/3506e1078ca02562f5e514c51fee6ed42cad028a/slides/imageSlides/imageSlides.gs#L57) for reference to make it more sense.

and the same wrong parameters are mentioned in the main site too. Please refer this guides [link](https://developers.google.com/apps-script/articles/image-slides#sample_script_plus_comments).

![image](https://user-images.githubusercontent.com/29234262/41894102-85e83b26-793b-11e8-8dde-8605b8a9b104.png)

**Comment by grant** [comment]
Thanks for reporting!
Feel free to send a Pull Request to fix these comments.

**Comment by SiddharthaSarma** [comment]
This is fixed. So closing this.
