### ISSUE TITLE
Disable trailing commas

### ISSUE THREAD

**Issue by grant** [gsuitedevs/apps-script-samples#43]
The Apps Script IDE/editor doesn't indent properly when there are trailing commas for object key/value pairs. Although, the runtime executes the code correctly.

Given this IDE limitation, it would be best for trailing commas to be explicitly removed from every sample.

## Proposal

Add this rule to our `.eslintrc.js` (https://eslint.org/docs/rules/comma-dangle)
```
"comma-dangle": "never"
```

**Comment by erickoledadevrel** [comment]
Sounds good to me.

**Comment by grant** [comment]
Fixed with d1241cc45155a6d3239a78d08a6379db96706884 ` "comma-dangle": ["error", "never"]`.
Luckily, eslint magically fixed all instances of these commas in all files.
