### ISSUE TITLE
Missing File upload Item in Class Form

### ISSUE THREAD

**Issue by arjunbazinga** [gsuitedevs/apps-script-samples#45]
I'm sorry if this isn't the right place for this, but I couldn't find anything in the reference regarding File upload item in the reference documentation. I am able to add a file upload field from the GUI but there isn't anything equivalent for apps script,  Is this not implemented yet?

**Comment by erickoledadevrel** [comment]
Unfortunately support for the file upload question has not been implemented yet in Apps Script. You can follow the feature request here: https://issuetracker.google.com/64924665
