### ISSUE TITLE
"Calendar" is not defined. (line 29"

### ISSUE THREAD

**Issue by cwlind** [gsuitedevs/apps-script-samples#46]
ReferenceError: "Calendar" is not defined. (line 29, file "calendar test")

Copy/pasted code "as is" into new project. Received above error. This is on a personal Google account, not corporate, so don't know if that is affecting anything.

**Comment by grant** [comment]
Thanks for reporting.

To add `Calendar`, follow the instructions to enable an Advanced Service:
https://developers.google.com/apps-script/guides/services/advanced#enabling_advanced_services

I'll make a note to add this to the sample comments.

**Comment by cwlind** [comment]
Doh! Rookie mistake. Sorry!
