### ISSUE TITLE
Google Apps Script - Problems parsing JSON

### ISSUE THREAD

**Issue by danieldeicide** [gsuitedevs/apps-script-samples#48]
Hi!

I am trying to update a GitHub json file from Google Apps Script (using UrlFetchApp.fetch() and I am getting the following error
```javascript
{"message":"Problems parsing JSON","documentation_url":"https://developer.github.com/v3/repos/contents/#update-a-file"}
```

The parameters are the following:
```javascript
var params = {
    "message": "This is  a test",
    "committer": {
      "name": "Daniel Deicide",
      "email": "example@example.com"
    },
    "content": "aGVsbG8sIHdvcmxkCg==", // this has to be Base64 encoded
    "sha": getSHA() //this is a function that returns sha of the file I want to update 
  };
    
  var options = {
    'method' : 'put',
    'payload' : params
  };
```

Could you please have a look and help me out with this? 

Thank you!

**Comment by grant** [comment]
It looks like the request to the GitHub API is not correct.

Did you check the link the error gave?
https://developer.github.com/v3/repos/contents/#update-a-file

**Comment by danieldeicide** [comment]
Yes, I tried with Postman (same setup) and it works

**Comment by danieldeicide** [comment]
I fixed it adding `JSON.stringify()` to `params`.
I will close the issue. Thank you for your time.
