### ISSUE TITLE
Forms Notifications sample doesn't support "collecting email addresses"

### ISSUE THREAD

**Issue by ramonsuarez** [gsuitedevs/apps-script-samples#50]
The app does not work with the new Google Forms and "collecting email addresses". 

When you choose to send an email to the person that has submitted the form it only offers you the choice of selecting the other questions to find the email, not the email question created by Google with the collect email addresses option.

![image](https://user-images.githubusercontent.com/1640484/42936313-0c3e5b0c-8b4c-11e8-9158-517c9b0aaebb.png)

**Comment by erickoledadevrel** [comment]
This sample was primarily created to teach developers how to create Forms Add-ons, and is not meant to be a comprehensive solution for this problem area. It looks like it should be possible to support this use case, but it isn't a high priority. If you or another member of the community is interested in contributing code please send us a PR.
