### ISSUE TITLE
Visible values are not currently supported

### ISSUE THREAD

**Issue by Mrityunjay1996** [gsuitedevs/apps-script-samples#53]
![screenshot 4](https://user-images.githubusercontent.com/39148049/43149029-21ab95cc-8f84-11e8-8903-b275de443ec0.png)

var sheetID ="" //Enter your sheet ID
 function test(){
   var filterCriteria=SpreadsheetApp.newFilterCriteria().setVisibleValues(["Test"]).build();
   SpreadsheetApp.setActiveSheet(SpreadsheetApp.openById(sheetID).getSheetByName("LP - Drives List"));
   Logger.log(SpreadsheetApp.getActiveSheet().getName())
   SpreadsheetApp.getActiveSheet().getRange(1,1,SpreadsheetApp.getActiveSheet().getLastRow(),SpreadsheetApp.getActiveSheet().getLastColumn()).createFilter().setColumnFilterCriteria(3, filterCriteria);
 }

**Comment by erickoledadevrel** [comment]
This issue tracker is for reporting bugs in the sample code in this repo. For reporting bugs in Apps Script please see the support page: 

https://developers.google.com/apps-script/support#bugs

From what I can tell, this method can only be used with Pivot Tables, and not regular sheet filters. We should mention that in the documentation.
