### ISSUE TITLE
Call App Script function only once during Authorization in Google Apps script [Gmail Add-on]

### ISSUE THREAD

**Issue by naveensinghal** [gsuitedevs/apps-script-samples#56]
Can someone please suggest how to make a Google Apps Script function execute only once during 'Authorize' button press from Gmail Add-on ? 

@grant Any suggestions please ?

Thanks,

**Comment by grant** [comment]
I'm not sure. @sqrrrl Do you know if there's an onAuth callback?

Other links:
https://developers.google.com/gmail/add-ons/how-tos/authorizing
https://github.com/gsuitedevs/gmail-add-ons-samples/issues

**Comment by sqrrrl** [comment]
Depends on the context -- is this for authorizing access to a 3P service? And do you want to run before or after auth?

For 3P auth, yes, you can do it. There's a callback that you're required to provide anyway to complete the oauth flow (see the github example in https://github.com/gsuitedevs/gmail-add-ons-samples)

For authorizing the add-on itself, no, there's no specific callback that takes place. Authorization happens before any of the add-on code is run. The only signal would be that this is the first time your code is running for that user. Of course the question is then "how do I know it's the first time?". For that, you can leverage PropertiesService.getUserProperties(). Check for the presence of a flag. If not set, it's the first time the user has run the add-on. Call whatever code you need in that case and set the flag. Subsequent executions would then see the flag and skip that code.

**Comment by grant** [comment]
Closed due to 30 day inactivity.
