### ISSUE TITLE
Invalid field selection files (line 5, file "Code")

### ISSUE THREAD

**Issue by gkiely** [gsuitedevs/apps-script-samples#57]
Followed this tutorial, got above error.
https://developers.google.com/drive/api/v3/quickstart/apps-script

Api is being called as I can see requests being made in google console.

![image](https://user-images.githubusercontent.com/1948935/44337713-e7882180-a4be-11e8-9ceb-7d2d1f974b8c.png)

**Comment by robertocastro** [comment]
Same error

**Comment by erickoledadevrel** [comment]
Please see issue #54.
