### ISSUE TITLE
[wrong repo, but lost] `GmailApp.createDraft()` should allow optional arguments

### ISSUE THREAD

**Issue by paxperscientiam** [gsuitedevs/apps-script-samples#59]
Hello!

I think the arguments for the `GmailApp.createDraft(recipient, subject, body)` method should be optional.

Case in point: Linking composition to a "new message" button without context (as opposed to a contextual wholly programmatic strategy). 

Example callback:
```typescript
function composeEmailNewCallback(e) {
    Logger.log("Composing new draft.");
    return CardService.newComposeActionResponseBuilder()
        .setGmailDraft(GmailApp.createDraft("", "", ""))
        .build();
}
```
Clearly, the three zero length strings are needless for the programmer. `GmailApp.createDraft()` should suffice.

Thanks!

_I know this is the wrong place, but I have no idea where this should be posted. Please let me know the correct place and then I'll delete and re-post elsewhere._

**Comment by erickoledadevrel** [comment]
As per the [Apps Script support page](https://developers.google.com/apps-script/support), feature requests should be posted to the [issue tracker](https://issuetracker.google.com/issues/new?component=191640&template=824113).
