### ISSUE TITLE
addGroupMember function - multiple groups

### ISSUE THREAD

**Issue by rpbaquing** [gsuitedevs/apps-script-samples#60]
I am using App Maker to automate the creation of users in GSuite. This includes adding the user to multiple groups. I used the multi-select widget for selecting multiple groups but I get this error message in the console:

SEVERE: Modifying records: (Error) : Record update failed: 'Groups' field value must be a valid option, but found 'group1@hooq.tv,group2@hooq.tv'.

How can I use the admin SDK for multiple group selection?

**Comment by erickoledadevrel** [comment]
This tracker is for issues with Apps Script sample code. For support with the Admin SDK Directory API, see this page: 

https://developers.google.com/admin-sdk/directory/support
