### ISSUE TITLE
Upload images for Slide directory README

### ISSUE THREAD

**Issue by asrivas** [gsuitedevs/apps-script-samples#61]
We have screenshots for the Translate and Progress Bars samples:
![quickstart-progress-bar-slides](https://user-images.githubusercontent.com/380123/45050203-9f383a00-b04e-11e8-9abf-042ce463a149.png)
![quickstart-translate-slides](https://user-images.githubusercontent.com/380123/45050204-9f383a00-b04e-11e8-9dc8-30fcc5e9fdd7.png)

**Comment by grant** [comment]
You may want to link directly to DevSite's source rather than `user-images.githubusercontent.com`, since this is the URL that broke.
