### ISSUE TITLE
Break line in the message

### ISSUE THREAD

**Issue by vbamagician** [gsuitedevs/apps-script-samples#64]
Like, Suppose, if the user wants to break the line in the email body message? then how we could reconstruct this code? 

My Email Response message is like below, 

> "Hello Dear Applicant, 
> 
> You're registered with us, thank you for your interest
> 
> ABC Ltd."

Please Guide.

**Comment by erickoledadevrel** [comment]
This issue tracker is for reporting bugs with our sample code. For general Q&A please see the options on the Apps Script support page:

https://developers.google.com/apps-script/support
