### ISSUE TITLE
Wrong variable referenced in Generating Google Slides from images Tutorial

### ISSUE THREAD

**Issue by kacrouse** [gsuitedevs/apps-script-samples#73]
[Lines 61, 65, and 66 of imageSlides](https://github.com/gsuitedevs/apps-script-samples/blob/master/slides/imageSlides/imageSlides.gs#L61-L66) reference the `presentation` variable. [At that point in the tutorial](https://developers.google.com/apps-script/articles/image-slides#improving_our_script), the `deck` variable is still being used to reference the presentation, so the script throws an error if you're following the tutorial step by step.

**Comment by erickoledadevrel** [comment]
Good catch, thanks!
