### ISSUE TITLE
No result or error when running sample drive script

### ISSUE THREAD

**Issue by tc127** [gsuitedevs/apps-script-samples#76]
Hi.

When running the following Quick Start script...

```js
 /**
 * Lists the names and IDs of up to 10 files.
 */
function listFiles() {
  var files = Drive.Files.list({
    fields: 'nextPageToken, items(id, title)',
    maxResults: 10
  }).items;
  for (var i = 0; i < files.length; i++) {
    var file = files[i];
    Logger.log('%s (%s)', file.title, file.id);
  }
}
```

...nothing happens. I've enabled the API and sorted out credentials, but when running this script it pops up along the top "Running function listFiles..." and then disappears.

This is all new to me. I was hoping to learn how to do other functions but I'm hesitant to go further if I can't get the stock script to run.

Any advice would be appreciated.

**Comment by grant** [comment]
Hi @tc127,
I wasn't able to reproduce the issue.
Were you able to look at the output with **View > Logs**?
Do you have files in drive.google.com?

You can use `Logger.log` to debug your code as well as the online debugger.
