### ISSUE TITLE
Add data studio samples from DevSite.

### ISSUE THREAD

**Issue by grant** [gsuitedevs/apps-script-samples#81]
See DevSite.
https://developers.google.com/datastudio/connector/error-handling#use_a_helper_function_to_log_and_throw_errors

**Comment by usernamefghh** [comment]
on issue

**Comment by grant** [comment]
Fixed with https://github.com/gsuitedevs/apps-script-samples/commit/c60c7acc1a90755fdd2a84bbece169ec1e0ddde5.
