### ISSUE TITLE
Sample uses undocumented API

### ISSUE THREAD

**Issue by wildeyes** [gsuitedevs/apps-script-samples#87]
## Expected Behavior
When installing @types/google-apps-script, I expect all samples to run without problem.
Sample URL: https://github.com/gsuitedevs/apps-script-samples/blob/master/advanced/calendar.gs#L66
Description: This line uses APIs not published by google-apps-script, or the [Calendar](https://developers.google.com/apps-script/reference/calendar/calendar) class.

## Actual Behavior
Either don't use internal APIs in public examples, or document the API in public docs.

## Steps to Reproduce the Problem

1. Compare between @types/google-apps-script/google-apps-script.calendar.d.ts and the aforementioned link.

**Comment by erickoledadevrel** [comment]
The TypeScript definitions for Apps Script were created by and maintained by the community, and are not official or canonical. The advanced services currently aren't included in the TypeScript definitions, but they are in our documentation:

https://developers.google.com/apps-script/advanced/calendar
