### ISSUE TITLE
Sheets.Spreadsheets.batchUpdate() is undefined

### ISSUE THREAD

**Issue by JeBuSBrian** [gsuitedevs/apps-script-samples#89]
## Expected Behavior

Sample URL: https://developers.google.com/sheets/api/quickstart/apps-script
Description: Should log values

## Actual Behavior
Throws error: "TypeError: Cannot read property "Values" from undefined."
It appears as thought Sheets.Spreadsheets is not working properly.

**Comment by erickoledadevrel** [comment]
I'm not able to reproduce that error. Please ensure that you haven't defined the variable `Sheets` anywhere else in your code.
