### ISSUE TITLE
[Feature Request] Manifest JSON schema

### ISSUE THREAD

**Issue by johnnyasantoss** [gsuitedevs/apps-script-samples#93]
Is it possible to have a json schema for both [this manifest](https://developers.google.com/apps-script/concepts/manifests) and the [gmail addon manifest](https://developers.google.com/gmail/add-ons/concepts/manifests)?

This would help a lot when developing extensions locally in code editors like VSCode. 🙂

**Comment by erickoledadevrel** [comment]
This issue tracker is for bugs and features with the samples in this repo. For product-level feature requests, please follow the instructions here:

https://developers.google.com/apps-script/support#missing_features

**Comment by johnnyasantoss** [comment]
[Done](https://issuetracker.google.com/issues/123173796).
Thanks! :)
