### ISSUE TITLE
How to do this by coding in files saved in my desktop?

### ISSUE THREAD

**Issue by sheikhrashid** [gsuitedevs/apps-script-samples#95]
Hi,

I have successfully run and implement all this in Google Apps script. Now I have simple HTML and JS file in my Desktop folder.  I am running the script on Button click.

How can I call Sheets API from there? 

Thanks

**Comment by grant** [comment]
Hi,
I think you may want to use StackOverflow for this question. This repo is only for questions about code samples here.
https://stackoverflow.com/questions/tagged/google-apps-script

You may use [clasp](https://github.com/google/clasp) to sync files to your desktop, but you probably want to test the web app with your add-on or web app.
