### ISSUE TITLE
Cannot specify deployment when creating triggers

### ISSUE THREAD

**Issue by andreadellacorte** [gsuitedevs/apps-script-samples#96]
## Expected Behavior

Sample URL: https://developers.google.com/apps-script/reference/script/trigger-builder
Description: Utilise the `TriggerBuilder` API to create a new trigger, specifying a deployment; the trigger is created pointing to the specified deployment, picking the correct version of the code

## Actual Behavior

The `TriggerBuilder` API doesn't allow to specify a deployment; all triggers default to HEAD and this cannot be changed.

## Steps to Reproduce the Problem

1. Try to create a Trigger
2. Cannot specify deployment

**Comment by erickoledadevrel** [comment]
This issue tracker is only for reporting issues with the sample code in this repo. For bugs or feature requests for Apps Script itself, please follow the guidelines on the support page:

https://developers.google.com/apps-script/support
