### ISSUE TITLE
Receive no email notification from installed app or manual copy into script editor

### ISSUE THREAD

**Issue by wincel** [gsuitedevs/apps-script-samples#99]
## Expected Behavior: receive email notification as form owner and recipient when form is submitted

Sample URL: https://docs.google.com/forms/d/e/1FAIpQLSdCxNeZ4vKHHugqxMatmxlSBFcqIhzux-MDueE-zGW84bp86Q/viewform?usp=sf_link

## Steps to Reproduce the Problem

1. Gsuite just installed, email in general works without problems
2. Installed Form Notifier from App Store, set notification configuration to "1" and for both, owner and responder to receive mail.
3. Filling out the form as linked & hit submit, nothing
4. Manually installed as per https://developers.google.com/gsuite/add-ons/editors/forms/quickstart/forms-notifications, hit submit, nothing

I just received from the https://developers.google.com/gsuite/add-ons/editors/forms/quickstart/forms-notifications manual install this notification: "No HTML file named CreatorNotification was found. (line 241, file "Code")" so it looks there is a name discrepancy between the add-on explanation and the code? I changed the template name to CreatorNotification.html instead of creatorNotification.html as described for the manual but still no email when I test it.

**Comment by wincel** [comment]
I looked into GSuite Developer Hub under executions and it says "Feb 20, 2019, 11:05:26 AM
ERROR
The form currently has no response destination. at sendCreatorNotification(notification:259) at respondToFormSubmit(notification:196)" over and over.

**Comment by wincel** [comment]
I've changed line 259:
```
//          DriveApp.getFileById(form.getDestinationId()).getUrl();
            DriveApp.getFileById("1FAIpQLSdCxNeZ4vKHHugqxMatmxlSBFcqIhzux-MDueE-zGW84bp86Q").getUrl();
```
And now the error is: 
Feb 20, 2019, 11:44:30 AM
ERROR
No item with the given ID could be found, or you do not have permission to access it. at sendCreatorNotification(notification:259) at respondToFormSubmit(notification:196)

**Comment by erickoledadevrel** [comment]
It looks like the code assumes that the Form is recording responses to a Google Sheet. Please ensure you are doing that and try again.

**Comment by wincel** [comment]
It is entering the information in a form, I can see the form and the entries made.

**Comment by erickoledadevrel** [comment]
I'm not able to reproduce the issue. Let me know if you can find steps to reproduce this on a new form.
